apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-bw0t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-bw0t
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-bw0t
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-bw0t
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-bw0t
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yyqq-tenant/rhtap-demo-app/hacbs-test-project-bw0t@sha256:9c1e6a088ddb9782165e5c17effb999a0ddcb475104a89d2857673c3e4ff6d40
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
